import type { MissionDefinition } from "../contracts/mission";

export const FIRST_CONTACT_MISSION = {
  id: "phase-0.first-contact",
  version: "spike-1",
  caseId: "case-001-midnight-badge",
  title: "First Contact",
  subtitle: "Bring the Investigation Console online",
  objective:
    "Run, personalize, predict, trace, intentionally break, and repair a tiny Python program, then complete a fresh Field Test.",
  primaryCapability: "Run real Python and distinguish source code from console output.",
  starterSource: 'print("Hello, Sophia!")',
  stageOrder: [
    "briefing",
    "first-run",
    "first-result",
    "personalize",
    "personalize-result",
    "prediction",
    "trace",
    "create-error",
    "error-feedback",
    "repair",
    "repair-result",
    "field-test",
    "field-result",
    "debrief",
    "reward",
    "complete",
  ],
  tasks: [
    {
      id: "first-run",
      kind: "run",
      stage: "first-run",
      title: "Send the first signal",
      prompt: "Run the program and notice where its message appears.",
      source: 'print("Hello, Sophia!")',
      runtime: "both",
      expectedStdout: "Hello, Sophia!\n",
    },
    {
      id: "personalize",
      kind: "personalize",
      stage: "personalize",
      title: "Make the signal yours",
      prompt: "Change only the text inside the quotation marks, then run it.",
      source: 'print("Hello, Sophia!")',
      runtime: "both",
    },
    {
      id: "predict-two-lines",
      kind: "predict",
      stage: "prediction",
      title: "Predict the sequence",
      prompt: "How many lines appear, and which message appears first?",
      source: 'print("Console online")\nprint("Case ready")',
      runtime: "none",
      allowNotSure: true,
    },
    {
      id: "trace-two-lines",
      kind: "trace",
      stage: "trace",
      title: "Inspect the Computer's Mind",
      prompt: "Step through the two lines and watch output accumulate.",
      source: 'print("Console online")\nprint("Case ready")',
      runtime: "none",
    },
    {
      id: "create-the-clue",
      kind: "break",
      stage: "create-error",
      title: "Create a controlled clue",
      prompt: "Remove the final quotation mark, run, and inspect what Python expected.",
      source: 'print("Case ready)',
      runtime: "both",
      expectedErrorCode: "unmatched-quote",
    },
    {
      id: "repair-the-clue",
      kind: "repair",
      stage: "repair",
      title: "Repair the signal",
      prompt: "Restore the matching quotation mark and run again.",
      source: 'print("Case ready)',
      runtime: "both",
      expectedStdout: "Case ready\n",
    },
    {
      id: "field-test",
      kind: "field-test",
      stage: "field-test",
      title: "Field Test",
      prompt: "Without a solution hint, print Investigation started exactly as shown.",
      source: 'print("")',
      runtime: "both",
      expectedStdout: "Investigation started\n",
    },
  ],
} as const satisfies MissionDefinition;
